
export const FIREBASE_AUTH_ANONYMOUSLY = 'FIREBASE_AUTH_ANONYMOUSLY'
export const FIREBASE_AUTH_WITH_PASSWORD = 'FIREBASE_AUTH_WITH_PASSWORD'
export const FIREBASE_CREATE_USER_AND_AUTH_WITH_PASSWORD = 'FIREBASE_CREATE_USER_AND_AUTH_WITH_PASSWORD'
export const FIREBASE_GET_AUTH = 'FIREBASE_GET_AUTH'
export const FIREBASE_ON_AUTH = 'FIREBASE_ON_AUTH'
export const FIREBASE_UNAUTH = 'FIREBASE_UNAUTH'
